name: CI

on: pull_request_target

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.sha}}
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v4
      with:
        python-version: "3.9.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      env:
        TOKEN: ${{ secrets.UNIT_TOKEN }}
      run: |
        pytest
