name: CI

on: pull_request_target

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.sha}}
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Test with pytest
      run: |
        TOKEN=${{ secrets.UNIT_TOKEN }} py.test
